export const Kereta = [
    {
        id: 1,
        nama : "Argo Wilis",
        kelas : "Eksekutif (H)",
        awal : "Stasiun Gambir",
        kotaAwal : "Jakarta (GMBR)",
        akhir : "Stasiun Surabaya",
        kotaAkhir : "Surabaya",
        berangkat : "05.00",
        tiba : "10.05",
        durasi : "5j 05m",
        harga : "250.000",
    },
    {
        id : 2,
        nama : "Wilis Argo",
        kelas : "Ekonomi (Q)",
        awal : "Gambir",
        kotaAwal : "Jakarta (GMBR)",
        akhir : "Surabaya",
        kotaAkhir : "Surabaya",
        berangkat : "05.00",
        tiba : "10.05",
        durasi : "5j 05m",
        harga : "250.000",
    },
    {
        id : 3,
        nama : "Anjasmoro",
        kelas : "Ekonomi (Q)",
        awal : "Gambir",
        KotaAwal : "Jakarta (GMBR)",
        akhir : "Surabaya",
        kotaAkhir : "Surabaya",
        berangkat : "05.00",
        tiba : "10.05",
        durasi : "5j 05m",
        harga : "250.000",
    },
     {
        id : 3,
        nama : "Anjas",
        kelas : "Ekonomi (Q)",
        awal : "Gambir",
        KotaAwal : "Jakarta (GMBR)",
        akhir : "Surabaya",
        kotaAkhir : "Surabaya",
        berangkat : "05.00",
        tiba : "10.05",
        durasi : "5j 05m",
        harga : "250.000",
    }
]
   